#! /bin/bash
#
#-----------------------------------------------------------------------------
# File:        run_questa
# Author:      Jonathan Bromley, Verilab
# Description: Run script to demonstrate use of vlab_probes package
#-----------------------------------------------------------------------------
# This run script is intended to illustrate the general compilation flow for the
# vlab_probes package with Questa.  It compiles and runs a very simple test.
# Depending on which version of Questa you use, the path to the systemc.so 
# shared library may need to be changed in the very last line of this file
# (vsim command)
#-----------------------------------------------------------------------------
# Copyright 2012 Verilab GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-----------------------------------------------------------------------------


# Use a local modelsim.ini for these experiments.
# First run will give a harmless warning for missing file.
#
export MODELSIM=./modelsim.ini

# Create a clean new work library.
#
rm -rf work
vlib work
vmap work ./work

# Compile the C code.  Using sccom is convenient because it
# automatically sets up the correct include directories,
# uses the right version of gcc to match Questa, and sets
# various other options in a useful way.  However, there
# is NO SystemC code here, and the SystemC simulation
# kernel is NOT used at runtime.
#
sccom ../src/vlab_probes.c

# Link to provide a shared object library "systemc.so".
# In a real environment you would probably need to control
# this step more carefully.
#
sccom -link

# Compile all the Verilog files.
#
vlog +acc=rn ../src/vlab_probes_pkg.sv ../test/test.sv

# Load the simulation and the shared object library.  Run the sim.
#
vsim -c -sv_lib work/_sc/linux_gcc-4.3.3/systemc -do 'puts stderr [time {run -all;}]; exit' test
